version: '2.1'

services:
  #Pi-hole Services
  pihole:
    build: ./balena-pihole/pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host
  # Set DNS1 and DNS2 service variables to 127.0.0.1#5053 on balenacloud to use dnscrypt-proxy for upstream DNS
  dnscrypt-proxy:
    build: ./balena-pihole/dnscrypt-proxy
    volumes:
      - 'dnscrypt_config:/config'
    ports:
      - '5053:5053/udp'

  # Minecraft Server Services
  mc-server:
    network_mode: host
    restart: always
    build: ./balena-minecraft-server/mc-server
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - serverfiles:/usr/src/serverfiles
      - servercache:/servercache
    ports:
      - "25565:25565/udp"
      - "25565:25565/tcp"
      - "25575:25575/udp"
      - "25575:25575/tcp"
  scp-server:
    network_mode: host
    restart: always
    build: ./balena-minecraft-server/scp-server
    privileged: false
    labels:
      io.balena.features.dbus: 1
    volumes:
      - serverfiles:/serverfiles
      - servercache:/servercache
    ports:
      - "22:22/udp"
      - "22:22/tcp"
  wifi-connect:
    build: ./balena-minecraft-server/wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'

volumes:
  pihole_config:
  dnsmasq_config:
  dnscrypt_config:
  serverfiles:
  servercache: